spring.application.name=backend

# Server config
server.port=8080
server.address=0.0.0.0
spring.h2.console.settings.web-allow-others=true

# Database config
spring.datasource.url=jdbc:h2:file:./src/main/resources/restaurant
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=restaurant_user
spring.datasource.password=secret_pwd
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.jpa.open-in-view=true

# make parsing from json fail when unknown attributes are found
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.hibernate.ddl-auto=create

# on first start load data from data.sql
spring.sql.init.mode=always

# number of tables to generate on startup
bartable.count=20


# Zugriff auf H2-Datenbank (Springboot muss laufen)
# Im Browser den Link http://localhost:8080/h2-console/ oeffnen.
# Im Fenster die Daten noch folgende Daten eingeben:
# JDBC URL: jdbc:h2:file:./src/main/resources/restaurant
# username und password wie oben